// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"git.anphabe.net/event/anphabe-event-hub/config"
	"github.com/stretchr/testify/mock"
)

// ConfigurationInterface is an autogenerated mock type for the ConfigurationInterface type
type ConfigurationInterface struct {
	mock.Mock
}

// GetConfig provides a mock function with given fields:
func (_m *ConfigurationInterface) GetConfig() *config.ConfigurationInfo {
	ret := _m.Called()

	var r0 *config.ConfigurationInfo
	if rf, ok := ret.Get(0).(func() *config.ConfigurationInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ConfigurationInfo)
		}
	}

	return r0
}
